version: "3.8"

volumes:
  rabbitmq_data:

services:
  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq

  ####################################
  # Atomic Microservice: Notifications
  ####################################
  notifications:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - rabbitmq
    env_file:
      - 'dev.env'
    environment:
      PYTHONUNBUFFERED: 1
