version: "3.8"

services:
  ####################################
  # RabbitMQ broker for testing  
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq-test
  ####################################
  # mysql database for testing
  ####################################
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notification
  ####################################
  # Notifications service under test
  ####################################
  notifications:
    build:
      context: ../
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - rabbitmq
    restart: always
    environment:
      db_conn: mysql+mysqlconnector://root:root@mysql:3306
      rabbitmq_host: rabbitmq
      rabbitmq_port: 5672
      password: notest
      sender_email: potatoesops@gmail.com
      smtp_email: smtp.gmail.com
      PYTHONUNBUFFERED: 1
  ##################################
  # Service for running pytest
  ##################################
  run-tests:
    build:
      context: ../
      dockerfile: ci/Dockerfile.test
    depends_on:
      - mysql
      - rabbitmq
      - notifications 
    environment:
      db_conn: mysql+mysqlconnector://root:root@mysql:3306
      rabbitmq_host: rabbitmq
      rabbitmq_port: 5672
      PYTHONUNBUFFERED: 1
